# Generated by Django 5.2.8 on 2026-01-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeafoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='seafood_images/')),
            ],
        ),
    ]
