# Generated by Django 6.0 on 2026-01-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0008_remove_product_category_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Оплата на картку Приват'), ('cash', 'Готівкою (тільки для самовивозу)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Не оплачено'), ('processing', 'В процесі'), ('paid', 'Оплачено')], default='not_paid', max_length=20),
        ),
    ]
