# Generated by Django 6.0 on 2026-01-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0011_remove_favorite_payment_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
