# Generated by Django 6.0 on 2026-01-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0012_order_payment_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='seafoodproduct',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='True — в наявності; False — немає в наявності'),
        ),
    ]
