# Generated by Django 5.2.8 on 2026-01-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0013_seafoodproduct_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='seafoodproduct',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
