# Generated by Django 5.2.8 on 2026-01-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0016_category_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seafoodproduct',
            name='package_size_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Якщо встановлено, товар продається упаковками цього розміру (в грамах), наприклад 500', null=True),
        ),
    ]
