# Generated by Django 5.2.8 on 2026-01-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0017_seafoodproduct_package_size_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='seafoodproduct',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='seafood.category'),
        ),
        migrations.AlterField(
            model_name='seafoodproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_products', to='seafood.category'),
        ),
    ]
