# Generated by Django 5.2.8 on 2026-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0018_seafoodproduct_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seafoodproduct',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ціна за 1 одиницю (вказуйте, якщо sold_in_units=True)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='seafoodproduct',
            name='sold_in_units',
            field=models.BooleanField(default=False, help_text='Позначте, якщо товар продається в одиницях (шт/банка) замість грами/пакету'),
        ),
        migrations.AddField(
            model_name='seafoodproduct',
            name='unit_label',
            field=models.CharField(blank=True, default='шт', help_text="Напис у шаблоні для одиниці (наприклад 'шт', 'банка')", max_length=30),
        ),
    ]
